In [11]:
#Nomber2

import numpy as np
z = np.random.random((6,6))
print(z)
print(z.sum(axis=1)/z.min(axis=0))

zmin, zmax = z[0].min(), z[0].max()

[[0.15226531 0.93343391 0.71655316 0.18143817 0.26433955 0.95810792]
 [0.43186112 0.19643162 0.54254841 0.36309678 0.20001814 0.54283263]
 [0.74365867 0.74852933 0.78338973 0.56149281 0.69001937 0.78761033]
 [0.99368344 0.17804223 0.78512992 0.27979806 0.37500012 0.95043141]
 [0.62423027 0.13324048 0.24439173 0.22420526 0.20672934 0.3741587 ]
 [0.61256083 0.44865235 0.98612652 0.50469383 0.32085361 0.43682132]]
[21.05626034 17.08781484 17.65485382 19.6325015   9.03395957  8.84573421]


In [12]:
#Nomber3

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
y = np.where(x==0)[0]-1
print(y)
print(x[y].max())

[1 3 4 7]
7


In [45]:
#Nomber1

a = np.random.random((10,3))
print(a)
c = [b[np.abs(b-0.5).argmin()] for b in a]
print(c)

[[0.75657222 0.58810438 0.25829742]
 [0.49401143 0.58677956 0.68897972]
 [0.91998026 0.56965726 0.95216015]
 [0.53619233 0.20604763 0.50106285]
 [0.51835306 0.57688982 0.5364753 ]
 [0.18060839 0.77402246 0.31047496]
 [0.55033923 0.59602813 0.19451695]
 [0.78548571 0.61572089 0.35187531]
 [0.01332054 0.6022539  0.35812087]
 [0.34639719 0.75817358 0.82414215]]
[0.5881043760350313, 0.49401142947578636, 0.5696572623361008, 0.5010628493510042, 0.5183530633151837, 0.31047496240855654, 0.5503392344737729, 0.6157208852316086, 0.6022538994065, 0.34639719456431595]
